spring:
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration/mysql
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/api_platform?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  # sqlite
  # datasource:
  #   url: jdbc:sqlite:d:/api-platform.db
  #   driver-class-name: org.sqlite.JDBC

logging:
  level:
    org.flywaydb.core: debug
    org.springframework.boot.flyway: debug
    org.springframework.boot.autoconfigure.flyway: debug