spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:sqlite:d:/api-platform.db
    driver-class-name: org.sqlite.JDBC

logging:
  level:
    org.flywaydb.core: debug
    org.springframework.boot.flyway: debug
    org.springframework.boot.autoconfigure.flyway: debug